// Generated by Wrangler on Fri Jun 14 2024 13:07:04 GMT-0300 (Horário Padrão de Brasília)
// by running `wrangler types`

interface Env {
	GOOGLE_API_KEY: KVNamespace;
}

import { type PlatformProxy } from "wrangler";

type Cloudflare = Omit<PlatformProxy<Env>, "dispose">;

declare module "@remix-run/cloudflare" {
  interface AppLoadContext {
    cloudflare: Cloudflare;
  }
}