name = "remix-cloudflare-template"
compatibility_date = "2024-02-11"

kv_namespaces = [
  { binding = "GOOGLE_API_KEY", id = "a02258fac15b4a4d8fd2244a57492186" }
]


[env.production]
kv_namespaces = [
    { binding = "GOOGLE_API_KEY", id = "a02258fac15b4a4d8fd2244a57492186" }
]
